#!/usr/bin/env bash

#    pacsync, for pacman synchronize with a given conf
#    Copyright (C) 2022  Cédric ROYER
#
#    This program is free software; you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation; either version 2 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License along
#    with this program; if not, write to the Free Software Foundation, Inc.,
#    51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.

set -euo pipefail

cmd=${1:-'help'}

script_dir="$(readlink -f "$(dirname "$0")")"

function print_help {
  cat << EOF
pacsync ([-h|--help|help]|sync)
  -h/--help/help    print this help
  sync              perform the sync

pacsync synchronize packages/groups declare in /etc/pacsync.d/* on current
system. Means it will add all missing packages/groups (and dependencies) and
remove all packages (and dependencies) not declared.
EOF
}

if [[ "$cmd" = 'help' ]] || [[ "$cmd" = '--help' ]] || [[ "$cmd" = '-h' ]]
then
  print_help
elif [[ "$cmd" = 'sync' ]]
then
  source "$script_dir/header.bash"
  source "$script_dir/libpacsync.bash"
  source "$script_dir/main.bash"
else
  echo "Unknown command ${cmd}"
  print_help
  exit 1
fi
